apiVersion: v1
kind: Service
metadata:
  name: static-site
  namespace: static-site
spec:
  selector:
    app: static-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort   # Use LoadBalancer for cloud, NodePort if using Minikube/Kind
