name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # runs when you push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Set image tag (using commit SHA)
      - name: Set image name
        run: echo "IMAGE=${{ secrets.DOCKER_USERNAME }}/static-site:${{ github.sha }}" >> $GITHUB_ENV

      # 4. Build & Push Docker image
      - name: Build and Push Docker image
        run: |
          docker build -t $IMAGE .
          docker push $IMAGE

      # 5. Update deployment.yaml with new image
      - name: Update Kubernetes manifests
        run: |
          sed -i "s|image:.*|image: $IMAGE|" k8s/deployment.yaml

      # 6. Commit & push updated manifests back to repo
      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image to $IMAGE"
          git push
